site_name: FastPlateOCR
site_author: ankandrew
site_description: Fast & Lightweight License Plate OCR
repo_url: https://github.com/ankandrew/fast-plate-ocr
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
nav:
  - Introduction: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Architecture: architecture.md
  - Contributing: contributing.md
  - Reference: reference.md
plugins:
  - search
  - mike:
      alias_type: symlink
      canonical_version: latest
  - mkdocstrings:
      handlers:
        python:
          paths: [ . ]
        options:
          members_order: source
          separate_signature: true
          filters: [ "!^_" ]
          docstring_options:
            ignore_init_summary: true
          merge_init_into_class: true
          show_signature_annotations: true
          signature_crossrefs: true
extra:
  version:
    provider: mike
  generator: false
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
      title: Page contents
