site_name: FastPlateOCR
site_author: ankandrew
site_description: Fast & Lightweight License Plate OCR
repo_url: https://github.com/ankandrew/fast-plate-ocr
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.path
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.footer
    - search.highlight
    - search.suggest
    - toc.follow
    - header.autohide
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
nav:
  - Get Started:
      - Introduction: index.md
      - Installation: installation.md
  - Inference:
      - Running Inference: inference/running_inference.md
      - Available Models: inference/model_zoo.md
  - Training:
      - intro: training/intro.md
      - CLI:
          - dataset_stats: training/cli/dataset_stats.md
          - export: training/cli/export.md
          - train: training/cli/train.md
          - valid: training/cli/valid.md
          - validate_dataset: training/cli/validate_dataset.md
          - visualize_augmentation: training/cli/visualize_augmentation.md
          - visualize_predictions: training/cli/visualize_predictions.md
  - Architecture: architecture.md
  - Contributing: contributing.md
  - Reference:
      - Inference:
          - LicensePlateRecognizer: reference/inference/inference_class.md
          - HUB: reference/inference/hub.md
      - Train:
          - XD: reference/train/model_builder.md
plugins:
  - search
  - mike:
      alias_type: symlink
      canonical_version: latest
  - mkdocstrings:
      handlers:
        python:
          paths: [ . ]
          options:
            members_order: source
            separate_signature: true
            filters: [ "!^_" ]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            show_object_full_path: false
            show_type_annotations: true
            show_variable_annotations: true
            signature_crossrefs: true
          inventories:
            - url: https://docs.python.org/3/objects.inv
              domains: [ py, std ]
            - url: https://typing-extensions.readthedocs.io/en/latest/objects.inv
extra:
  version:
    provider: mike
  generator: false
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/fast-plate-ocr/
    - icon: fontawesome/brands/github
      link: https://github.com/ankandrew/fast-plate-ocr
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
      title: Page contents
